package com.mciter.commonbeans;

// Generated 26 Jun, 2013 5:08:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblEmailconfigMaster generated by hbm2java
 */
public class TblEmailconfigMaster implements java.io.Serializable {

	private String emailconfigId;
	private String emailconfigName;
	private String emailconfigEmailid;
	private String emailconfigPass;
	private String emailconfigType;
	private String emailconfigInhost;
	private String emailconfigOuthost;
	private String emailconfigInport;
	private String emailconfigOutport;
	private String emailconfigStatus;

	public TblEmailconfigMaster() {
	}

	public TblEmailconfigMaster(String emailconfigId) {
		this.emailconfigId = emailconfigId;
	}

	public TblEmailconfigMaster(String emailconfigId, String emailconfigName,
			String emailconfigEmailid, String emailconfigPass,
			String emailconfigType, String emailconfigInhost,
			String emailconfigOuthost, String emailconfigInport,
			String emailconfigOutport, String emailconfigStatus) {
		this.emailconfigId = emailconfigId;
		this.emailconfigName = emailconfigName;
		this.emailconfigEmailid = emailconfigEmailid;
		this.emailconfigPass = emailconfigPass;
		this.emailconfigType = emailconfigType;
		this.emailconfigInhost = emailconfigInhost;
		this.emailconfigOuthost = emailconfigOuthost;
		this.emailconfigInport = emailconfigInport;
		this.emailconfigOutport = emailconfigOutport;
		this.emailconfigStatus = emailconfigStatus;
	}

	public String getEmailconfigId() {
		return this.emailconfigId;
	}

	public void setEmailconfigId(String emailconfigId) {
		this.emailconfigId = emailconfigId;
	}

	public String getEmailconfigName() {
		return this.emailconfigName;
	}

	public void setEmailconfigName(String emailconfigName) {
		this.emailconfigName = emailconfigName;
	}

	public String getEmailconfigEmailid() {
		return this.emailconfigEmailid;
	}

	public void setEmailconfigEmailid(String emailconfigEmailid) {
		this.emailconfigEmailid = emailconfigEmailid;
	}

	public String getEmailconfigPass() {
		return this.emailconfigPass;
	}

	public void setEmailconfigPass(String emailconfigPass) {
		this.emailconfigPass = emailconfigPass;
	}

	public String getEmailconfigType() {
		return this.emailconfigType;
	}

	public void setEmailconfigType(String emailconfigType) {
		this.emailconfigType = emailconfigType;
	}

	public String getEmailconfigInhost() {
		return this.emailconfigInhost;
	}

	public void setEmailconfigInhost(String emailconfigInhost) {
		this.emailconfigInhost = emailconfigInhost;
	}

	public String getEmailconfigOuthost() {
		return this.emailconfigOuthost;
	}

	public void setEmailconfigOuthost(String emailconfigOuthost) {
		this.emailconfigOuthost = emailconfigOuthost;
	}

	public String getEmailconfigInport() {
		return this.emailconfigInport;
	}

	public void setEmailconfigInport(String emailconfigInport) {
		this.emailconfigInport = emailconfigInport;
	}

	public String getEmailconfigOutport() {
		return this.emailconfigOutport;
	}

	public void setEmailconfigOutport(String emailconfigOutport) {
		this.emailconfigOutport = emailconfigOutport;
	}

	public String getEmailconfigStatus() {
		return this.emailconfigStatus;
	}

	public void setEmailconfigStatus(String emailconfigStatus) {
		this.emailconfigStatus = emailconfigStatus;
	}

}
