package com.mciter.commonbeans;

// Generated 6 Aug, 2012 8:03:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblMainqpatternDetails generated by hbm2java
 */
public class TblMainqpatternDetails implements java.io.Serializable {

	private Integer mpId;
	private TblQuestionsMaster tblQuestionsMaster;
	private TblPapermainqDetails tblPapermainqDetails;
	private int mpMarks;
	private int mpTag;
	private Set<TblStudentpaperSession> tblStudentpaperSessions = new HashSet<TblStudentpaperSession>(
			0);

	public TblMainqpatternDetails() {
	}

	public TblMainqpatternDetails(TblQuestionsMaster tblQuestionsMaster,
			TblPapermainqDetails tblPapermainqDetails, int mpMarks, int mpTag) {
		this.tblQuestionsMaster = tblQuestionsMaster;
		this.tblPapermainqDetails = tblPapermainqDetails;
		this.mpMarks = mpMarks;
		this.mpTag = mpTag;
	}

	public TblMainqpatternDetails(TblQuestionsMaster tblQuestionsMaster,
			TblPapermainqDetails tblPapermainqDetails, int mpMarks, int mpTag,
			Set<TblStudentpaperSession> tblStudentpaperSessions) {
		this.tblQuestionsMaster = tblQuestionsMaster;
		this.tblPapermainqDetails = tblPapermainqDetails;
		this.mpMarks = mpMarks;
		this.mpTag = mpTag;
		this.tblStudentpaperSessions = tblStudentpaperSessions;
	}

	public Integer getMpId() {
		return this.mpId;
	}

	public void setMpId(Integer mpId) {
		this.mpId = mpId;
	}

	public TblQuestionsMaster getTblQuestionsMaster() {
		return this.tblQuestionsMaster;
	}

	public void setTblQuestionsMaster(TblQuestionsMaster tblQuestionsMaster) {
		this.tblQuestionsMaster = tblQuestionsMaster;
	}

	public TblPapermainqDetails getTblPapermainqDetails() {
		return this.tblPapermainqDetails;
	}

	public void setTblPapermainqDetails(
			TblPapermainqDetails tblPapermainqDetails) {
		this.tblPapermainqDetails = tblPapermainqDetails;
	}

	public int getMpMarks() {
		return this.mpMarks;
	}

	public void setMpMarks(int mpMarks) {
		this.mpMarks = mpMarks;
	}

	public int getMpTag() {
		return this.mpTag;
	}

	public void setMpTag(int mpTag) {
		this.mpTag = mpTag;
	}

	public Set<TblStudentpaperSession> getTblStudentpaperSessions() {
		return this.tblStudentpaperSessions;
	}

	public void setTblStudentpaperSessions(
			Set<TblStudentpaperSession> tblStudentpaperSessions) {
		this.tblStudentpaperSessions = tblStudentpaperSessions;
	}

}
