package com.mciter.commonbeans;

// Generated 6 Aug, 2012 8:03:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblPaperpatternMaster generated by hbm2java
 */
public class TblPaperpatternMaster implements java.io.Serializable {

	private Integer ppId;
	private String ppName;
	private int ppTotal;
	private int ppPassingMarks;
	private int ppGraceMarks;
	private int ppTag;
	private int ppNegativeMarks;
	private String ppPaperType;
	private Set<TblPapermainqDetails> tblPapermainqDetailses = new HashSet<TblPapermainqDetails>(
			0);
	private Set<TblStudentexamConduct> tblStudentexamConducts = new HashSet<TblStudentexamConduct>(
			0);

	public TblPaperpatternMaster() {
	}

	public TblPaperpatternMaster(String ppName, int ppTotal,
			int ppPassingMarks, int ppGraceMarks, int ppTag,
			int ppNegativeMarks, String ppPaperType) {
		this.ppName = ppName;
		this.ppTotal = ppTotal;
		this.ppPassingMarks = ppPassingMarks;
		this.ppGraceMarks = ppGraceMarks;
		this.ppTag = ppTag;
		this.ppNegativeMarks = ppNegativeMarks;
		this.ppPaperType = ppPaperType;
	}

	public TblPaperpatternMaster(String ppName, int ppTotal,
			int ppPassingMarks, int ppGraceMarks, int ppTag,
			int ppNegativeMarks, String ppPaperType,
			Set<TblPapermainqDetails> tblPapermainqDetailses,
			Set<TblStudentexamConduct> tblStudentexamConducts) {
		this.ppName = ppName;
		this.ppTotal = ppTotal;
		this.ppPassingMarks = ppPassingMarks;
		this.ppGraceMarks = ppGraceMarks;
		this.ppTag = ppTag;
		this.ppNegativeMarks = ppNegativeMarks;
		this.ppPaperType = ppPaperType;
		this.tblPapermainqDetailses = tblPapermainqDetailses;
		this.tblStudentexamConducts = tblStudentexamConducts;
	}

	public Integer getPpId() {
		return this.ppId;
	}

	public void setPpId(Integer ppId) {
		this.ppId = ppId;
	}

	public String getPpName() {
		return this.ppName;
	}

	public void setPpName(String ppName) {
		this.ppName = ppName;
	}

	public int getPpTotal() {
		return this.ppTotal;
	}

	public void setPpTotal(int ppTotal) {
		this.ppTotal = ppTotal;
	}

	public int getPpPassingMarks() {
		return this.ppPassingMarks;
	}

	public void setPpPassingMarks(int ppPassingMarks) {
		this.ppPassingMarks = ppPassingMarks;
	}

	public int getPpGraceMarks() {
		return this.ppGraceMarks;
	}

	public void setPpGraceMarks(int ppGraceMarks) {
		this.ppGraceMarks = ppGraceMarks;
	}

	public int getPpTag() {
		return this.ppTag;
	}

	public void setPpTag(int ppTag) {
		this.ppTag = ppTag;
	}

	public int getPpNegativeMarks() {
		return this.ppNegativeMarks;
	}

	public void setPpNegativeMarks(int ppNegativeMarks) {
		this.ppNegativeMarks = ppNegativeMarks;
	}

	public String getPpPaperType() {
		return this.ppPaperType;
	}

	public void setPpPaperType(String ppPaperType) {
		this.ppPaperType = ppPaperType;
	}

	public Set<TblPapermainqDetails> getTblPapermainqDetailses() {
		return this.tblPapermainqDetailses;
	}

	public void setTblPapermainqDetailses(
			Set<TblPapermainqDetails> tblPapermainqDetailses) {
		this.tblPapermainqDetailses = tblPapermainqDetailses;
	}

	public Set<TblStudentexamConduct> getTblStudentexamConducts() {
		return this.tblStudentexamConducts;
	}

	public void setTblStudentexamConducts(
			Set<TblStudentexamConduct> tblStudentexamConducts) {
		this.tblStudentexamConducts = tblStudentexamConducts;
	}

}
