package com.mciter.commonbeans;

// Generated 6 Aug, 2012 8:03:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblQuestionsMaster generated by hbm2java
 */
public class TblQuestionsMaster implements java.io.Serializable {

	private Integer QId;
	private TblUserMaster tblUserMaster;
	private TblMarksMaster tblMarksMaster;
	private TblQuestioncategoryMaster tblQuestioncategoryMaster;
	private String QName;
	private String QDesc;
	private boolean QMultiSelect;
	private int QOption;
	private int QTag;
	private Set<TblQuestionOptions> tblQuestionOptionses = new HashSet<TblQuestionOptions>(
			0);
	private Set<TblMainqpatternDetails> tblMainqpatternDetailses = new HashSet<TblMainqpatternDetails>(
			0);

	public TblQuestionsMaster() {
	}

	public TblQuestionsMaster(TblUserMaster tblUserMaster,
			TblMarksMaster tblMarksMaster,
			TblQuestioncategoryMaster tblQuestioncategoryMaster, String QName,
			String QDesc, boolean QMultiSelect, int QOption, int QTag) {
		this.tblUserMaster = tblUserMaster;
		this.tblMarksMaster = tblMarksMaster;
		this.tblQuestioncategoryMaster = tblQuestioncategoryMaster;
		this.QName = QName;
		this.QDesc = QDesc;
		this.QMultiSelect = QMultiSelect;
		this.QOption = QOption;
		this.QTag = QTag;
	}

	public TblQuestionsMaster(TblUserMaster tblUserMaster,
			TblMarksMaster tblMarksMaster,
			TblQuestioncategoryMaster tblQuestioncategoryMaster, String QName,
			String QDesc, boolean QMultiSelect, int QOption, int QTag,
			Set<TblQuestionOptions> tblQuestionOptionses,
			Set<TblMainqpatternDetails> tblMainqpatternDetailses) {
		this.tblUserMaster = tblUserMaster;
		this.tblMarksMaster = tblMarksMaster;
		this.tblQuestioncategoryMaster = tblQuestioncategoryMaster;
		this.QName = QName;
		this.QDesc = QDesc;
		this.QMultiSelect = QMultiSelect;
		this.QOption = QOption;
		this.QTag = QTag;
		this.tblQuestionOptionses = tblQuestionOptionses;
		this.tblMainqpatternDetailses = tblMainqpatternDetailses;
	}

	public Integer getQId() {
		return this.QId;
	}

	public void setQId(Integer QId) {
		this.QId = QId;
	}

	public TblUserMaster getTblUserMaster() {
		return this.tblUserMaster;
	}

	public void setTblUserMaster(TblUserMaster tblUserMaster) {
		this.tblUserMaster = tblUserMaster;
	}

	public TblMarksMaster getTblMarksMaster() {
		return this.tblMarksMaster;
	}

	public void setTblMarksMaster(TblMarksMaster tblMarksMaster) {
		this.tblMarksMaster = tblMarksMaster;
	}

	public TblQuestioncategoryMaster getTblQuestioncategoryMaster() {
		return this.tblQuestioncategoryMaster;
	}

	public void setTblQuestioncategoryMaster(
			TblQuestioncategoryMaster tblQuestioncategoryMaster) {
		this.tblQuestioncategoryMaster = tblQuestioncategoryMaster;
	}

	public String getQName() {
		return this.QName;
	}

	public void setQName(String QName) {
		this.QName = QName;
	}

	public String getQDesc() {
		return this.QDesc;
	}

	public void setQDesc(String QDesc) {
		this.QDesc = QDesc;
	}

	public boolean isQMultiSelect() {
		return this.QMultiSelect;
	}

	public void setQMultiSelect(boolean QMultiSelect) {
		this.QMultiSelect = QMultiSelect;
	}

	public int getQOption() {
		return this.QOption;
	}

	public void setQOption(int QOption) {
		this.QOption = QOption;
	}

	public int getQTag() {
		return this.QTag;
	}

	public void setQTag(int QTag) {
		this.QTag = QTag;
	}

	public Set<TblQuestionOptions> getTblQuestionOptionses() {
		return this.tblQuestionOptionses;
	}

	public void setTblQuestionOptionses(
			Set<TblQuestionOptions> tblQuestionOptionses) {
		this.tblQuestionOptionses = tblQuestionOptionses;
	}

	public Set<TblMainqpatternDetails> getTblMainqpatternDetailses() {
		return this.tblMainqpatternDetailses;
	}

	public void setTblMainqpatternDetailses(
			Set<TblMainqpatternDetails> tblMainqpatternDetailses) {
		this.tblMainqpatternDetailses = tblMainqpatternDetailses;
	}

}
