package com.mciter.commonbeans;

// Generated 6 Aug, 2012 8:03:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblTypingtestSession generated by hbm2java
 */
public class TblTypingtestSession implements java.io.Serializable {

	private Integer typesesId;
	private TblTypingtestDetails tblTypingtestDetails;
	private TblStudentexamConduct tblStudentexamConduct;
	private String typesesDesc;
	private boolean typesesCompletedOnTime;
	private int typesesMistakesdone;
	private String typesesTag;

	public TblTypingtestSession() {
	}

	public TblTypingtestSession(TblTypingtestDetails tblTypingtestDetails,
			TblStudentexamConduct tblStudentexamConduct, String typesesDesc,
			boolean typesesCompletedOnTime, int typesesMistakesdone,
			String typesesTag) {
		this.tblTypingtestDetails = tblTypingtestDetails;
		this.tblStudentexamConduct = tblStudentexamConduct;
		this.typesesDesc = typesesDesc;
		this.typesesCompletedOnTime = typesesCompletedOnTime;
		this.typesesMistakesdone = typesesMistakesdone;
		this.typesesTag = typesesTag;
	}

	public Integer getTypesesId() {
		return this.typesesId;
	}

	public void setTypesesId(Integer typesesId) {
		this.typesesId = typesesId;
	}

	public TblTypingtestDetails getTblTypingtestDetails() {
		return this.tblTypingtestDetails;
	}

	public void setTblTypingtestDetails(
			TblTypingtestDetails tblTypingtestDetails) {
		this.tblTypingtestDetails = tblTypingtestDetails;
	}

	public TblStudentexamConduct getTblStudentexamConduct() {
		return this.tblStudentexamConduct;
	}

	public void setTblStudentexamConduct(
			TblStudentexamConduct tblStudentexamConduct) {
		this.tblStudentexamConduct = tblStudentexamConduct;
	}

	public String getTypesesDesc() {
		return this.typesesDesc;
	}

	public void setTypesesDesc(String typesesDesc) {
		this.typesesDesc = typesesDesc;
	}

	public boolean isTypesesCompletedOnTime() {
		return this.typesesCompletedOnTime;
	}

	public void setTypesesCompletedOnTime(boolean typesesCompletedOnTime) {
		this.typesesCompletedOnTime = typesesCompletedOnTime;
	}

	public int getTypesesMistakesdone() {
		return this.typesesMistakesdone;
	}

	public void setTypesesMistakesdone(int typesesMistakesdone) {
		this.typesesMistakesdone = typesesMistakesdone;
	}

	public String getTypesesTag() {
		return this.typesesTag;
	}

	public void setTypesesTag(String typesesTag) {
		this.typesesTag = typesesTag;
	}

}
