package com.mciter.commonbeans;

// Generated 6 Aug, 2012 8:03:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblQuestioncategoryMaster generated by hbm2java
 */
public class TblQuestioncategoryMaster implements java.io.Serializable {

	private Integer qcId;
	private TblCategoryMaster tblCategoryMaster;
	private String qcName;
	private int qcTag;
	private Set<TblStudentresultDetails> tblStudentresultDetailses = new HashSet<TblStudentresultDetails>(
			0);
	private Set<TblStudentCourseDetails> tblStudentCourseDetailses = new HashSet<TblStudentCourseDetails>(
			0);
	private Set<TblTypingtestMaster> tblTypingtestMasters = new HashSet<TblTypingtestMaster>(
			0);
	private Set<TblStudentDetails> tblStudentDetailses = new HashSet<TblStudentDetails>(
			0);
	private Set<TblQuestionsMaster> tblQuestionsMasters = new HashSet<TblQuestionsMaster>(
			0);
	private Set<TblStudentexamConduct> tblStudentexamConducts = new HashSet<TblStudentexamConduct>(
			0);

	public TblQuestioncategoryMaster() {
	}

	public TblQuestioncategoryMaster(TblCategoryMaster tblCategoryMaster,
			String qcName, int qcTag) {
		this.tblCategoryMaster = tblCategoryMaster;
		this.qcName = qcName;
		this.qcTag = qcTag;
	}

	public TblQuestioncategoryMaster(TblCategoryMaster tblCategoryMaster,
			String qcName, int qcTag,
			Set<TblStudentresultDetails> tblStudentresultDetailses,
			Set<TblStudentCourseDetails> tblStudentCourseDetailses,
			Set<TblTypingtestMaster> tblTypingtestMasters,
			Set<TblStudentDetails> tblStudentDetailses,
			Set<TblQuestionsMaster> tblQuestionsMasters,
			Set<TblStudentexamConduct> tblStudentexamConducts) {
		this.tblCategoryMaster = tblCategoryMaster;
		this.qcName = qcName;
		this.qcTag = qcTag;
		this.tblStudentresultDetailses = tblStudentresultDetailses;
		this.tblStudentCourseDetailses = tblStudentCourseDetailses;
		this.tblTypingtestMasters = tblTypingtestMasters;
		this.tblStudentDetailses = tblStudentDetailses;
		this.tblQuestionsMasters = tblQuestionsMasters;
		this.tblStudentexamConducts = tblStudentexamConducts;
	}

	public Integer getQcId() {
		return this.qcId;
	}

	public void setQcId(Integer qcId) {
		this.qcId = qcId;
	}

	public TblCategoryMaster getTblCategoryMaster() {
		return this.tblCategoryMaster;
	}

	public void setTblCategoryMaster(TblCategoryMaster tblCategoryMaster) {
		this.tblCategoryMaster = tblCategoryMaster;
	}

	public String getQcName() {
		return this.qcName;
	}

	public void setQcName(String qcName) {
		this.qcName = qcName;
	}

	public int getQcTag() {
		return this.qcTag;
	}

	public void setQcTag(int qcTag) {
		this.qcTag = qcTag;
	}

	public Set<TblStudentresultDetails> getTblStudentresultDetailses() {
		return this.tblStudentresultDetailses;
	}

	public void setTblStudentresultDetailses(
			Set<TblStudentresultDetails> tblStudentresultDetailses) {
		this.tblStudentresultDetailses = tblStudentresultDetailses;
	}

	public Set<TblStudentCourseDetails> getTblStudentCourseDetailses() {
		return this.tblStudentCourseDetailses;
	}

	public void setTblStudentCourseDetailses(
			Set<TblStudentCourseDetails> tblStudentCourseDetailses) {
		this.tblStudentCourseDetailses = tblStudentCourseDetailses;
	}

	public Set<TblTypingtestMaster> getTblTypingtestMasters() {
		return this.tblTypingtestMasters;
	}

	public void setTblTypingtestMasters(
			Set<TblTypingtestMaster> tblTypingtestMasters) {
		this.tblTypingtestMasters = tblTypingtestMasters;
	}

	public Set<TblStudentDetails> getTblStudentDetailses() {
		return this.tblStudentDetailses;
	}

	public void setTblStudentDetailses(
			Set<TblStudentDetails> tblStudentDetailses) {
		this.tblStudentDetailses = tblStudentDetailses;
	}

	public Set<TblQuestionsMaster> getTblQuestionsMasters() {
		return this.tblQuestionsMasters;
	}

	public void setTblQuestionsMasters(
			Set<TblQuestionsMaster> tblQuestionsMasters) {
		this.tblQuestionsMasters = tblQuestionsMasters;
	}

	public Set<TblStudentexamConduct> getTblStudentexamConducts() {
		return this.tblStudentexamConducts;
	}

	public void setTblStudentexamConducts(
			Set<TblStudentexamConduct> tblStudentexamConducts) {
		this.tblStudentexamConducts = tblStudentexamConducts;
	}

}
