package com.mciter.commonbeans;

// Generated 31 Aug, 2012 5:51:31 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblTypingtestMaster generated by hbm2java
 */
public class TblTypingtestMaster implements java.io.Serializable {

	private Integer typetId;
	private int qcId;
	private String typetDesc;
	private int fontId;
	private String typetTypingtype;
	private int typetTag;
	private String typetAlias;

	public TblTypingtestMaster() {
	}

	public TblTypingtestMaster(int qcId, String typetDesc, int fontId,
			String typetTypingtype, int typetTag, String typetAlias) {
		this.qcId = qcId;
		this.typetDesc = typetDesc;
		this.fontId = fontId;
		this.typetTypingtype = typetTypingtype;
		this.typetTag = typetTag;
		this.typetAlias = typetAlias;
	}

	public Integer getTypetId() {
		return this.typetId;
	}

	public void setTypetId(Integer typetId) {
		this.typetId = typetId;
	}

	public int getQcId() {
		return this.qcId;
	}

	public void setQcId(int qcId) {
		this.qcId = qcId;
	}

	public String getTypetDesc() {
		return this.typetDesc;
	}

	public void setTypetDesc(String typetDesc) {
		this.typetDesc = typetDesc;
	}

	public int getFontId() {
		return this.fontId;
	}

	public void setFontId(int fontId) {
		this.fontId = fontId;
	}

	public String getTypetTypingtype() {
		return this.typetTypingtype;
	}

	public void setTypetTypingtype(String typetTypingtype) {
		this.typetTypingtype = typetTypingtype;
	}

	public int getTypetTag() {
		return this.typetTag;
	}

	public void setTypetTag(int typetTag) {
		this.typetTag = typetTag;
	}

	public String getTypetAlias() {
		return this.typetAlias;
	}

	public void setTypetAlias(String typetAlias) {
		this.typetAlias = typetAlias;
	}

}
