package com.mciter.commonbeans;

// Generated 6 Aug, 2012 8:03:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblStudentDetails generated by hbm2java
 */
public class TblStudentDetails implements java.io.Serializable {

	private String studentid;
	private TblCenterDetails tblCenterDetails;
	private TblQuestioncategoryMaster tblQuestioncategoryMaster;
	private String firstname;
	private String middlename;
	private String lastname;
	private String dayofbirth;
	private String monthofbirth;
	private String yearofbirth;
	private String age;
	private String gender;
	private String maritalstatus;
	private String addressforcorrespondence;
	private String address;
	private String suburb;
	private String citytownvillage;
	private String pincode;
	private String state;
	private String district;
	private String tahsil;
	private String mobileown;
	private String mobileother;
	private String emailid;
	private String modeofpayment;
	private String categoryofstudent;
	private int tag;
	private String active;
	private Date registerationdate;
	private Set<TblStudentexamConduct> tblStudentexamConducts = new HashSet<TblStudentexamConduct>(
			0);
	private Set<TblStudentCourseDetails> tblStudentCourseDetailses = new HashSet<TblStudentCourseDetails>(
			0);

	public TblStudentDetails() {
	}

	public TblStudentDetails(String studentid,
			TblQuestioncategoryMaster tblQuestioncategoryMaster, int tag,
			String active) {
		this.studentid = studentid;
		this.tblQuestioncategoryMaster = tblQuestioncategoryMaster;
		this.tag = tag;
		this.active = active;
	}

	public TblStudentDetails(String studentid,
			TblCenterDetails tblCenterDetails,
			TblQuestioncategoryMaster tblQuestioncategoryMaster,
			String firstname, String middlename, String lastname,
			String dayofbirth, String monthofbirth, String yearofbirth,
			String age, String gender, String maritalstatus,
			String addressforcorrespondence, String address, String suburb,
			String citytownvillage, String pincode, String state,
			String district, String tahsil, String mobileown,
			String mobileother, String emailid, String modeofpayment,
			String categoryofstudent, int tag, String active,
			Date registerationdate,
			Set<TblStudentexamConduct> tblStudentexamConducts,
			Set<TblStudentCourseDetails> tblStudentCourseDetailses) {
		this.studentid = studentid;
		this.tblCenterDetails = tblCenterDetails;
		this.tblQuestioncategoryMaster = tblQuestioncategoryMaster;
		this.firstname = firstname;
		this.middlename = middlename;
		this.lastname = lastname;
		this.dayofbirth = dayofbirth;
		this.monthofbirth = monthofbirth;
		this.yearofbirth = yearofbirth;
		this.age = age;
		this.gender = gender;
		this.maritalstatus = maritalstatus;
		this.addressforcorrespondence = addressforcorrespondence;
		this.address = address;
		this.suburb = suburb;
		this.citytownvillage = citytownvillage;
		this.pincode = pincode;
		this.state = state;
		this.district = district;
		this.tahsil = tahsil;
		this.mobileown = mobileown;
		this.mobileother = mobileother;
		this.emailid = emailid;
		this.modeofpayment = modeofpayment;
		this.categoryofstudent = categoryofstudent;
		this.tag = tag;
		this.active = active;
		this.registerationdate = registerationdate;
		this.tblStudentexamConducts = tblStudentexamConducts;
		this.tblStudentCourseDetailses = tblStudentCourseDetailses;
	}

	public String getStudentid() {
		return this.studentid;
	}

	public void setStudentid(String studentid) {
		this.studentid = studentid;
	}

	public TblCenterDetails getTblCenterDetails() {
		return this.tblCenterDetails;
	}

	public void setTblCenterDetails(TblCenterDetails tblCenterDetails) {
		this.tblCenterDetails = tblCenterDetails;
	}

	public TblQuestioncategoryMaster getTblQuestioncategoryMaster() {
		return this.tblQuestioncategoryMaster;
	}

	public void setTblQuestioncategoryMaster(
			TblQuestioncategoryMaster tblQuestioncategoryMaster) {
		this.tblQuestioncategoryMaster = tblQuestioncategoryMaster;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getMiddlename() {
		return this.middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getDayofbirth() {
		return this.dayofbirth;
	}

	public void setDayofbirth(String dayofbirth) {
		this.dayofbirth = dayofbirth;
	}

	public String getMonthofbirth() {
		return this.monthofbirth;
	}

	public void setMonthofbirth(String monthofbirth) {
		this.monthofbirth = monthofbirth;
	}

	public String getYearofbirth() {
		return this.yearofbirth;
	}

	public void setYearofbirth(String yearofbirth) {
		this.yearofbirth = yearofbirth;
	}

	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getMaritalstatus() {
		return this.maritalstatus;
	}

	public void setMaritalstatus(String maritalstatus) {
		this.maritalstatus = maritalstatus;
	}

	public String getAddressforcorrespondence() {
		return this.addressforcorrespondence;
	}

	public void setAddressforcorrespondence(String addressforcorrespondence) {
		this.addressforcorrespondence = addressforcorrespondence;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getSuburb() {
		return this.suburb;
	}

	public void setSuburb(String suburb) {
		this.suburb = suburb;
	}

	public String getCitytownvillage() {
		return this.citytownvillage;
	}

	public void setCitytownvillage(String citytownvillage) {
		this.citytownvillage = citytownvillage;
	}

	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getTahsil() {
		return this.tahsil;
	}

	public void setTahsil(String tahsil) {
		this.tahsil = tahsil;
	}

	public String getMobileown() {
		return this.mobileown;
	}

	public void setMobileown(String mobileown) {
		this.mobileown = mobileown;
	}

	public String getMobileother() {
		return this.mobileother;
	}

	public void setMobileother(String mobileother) {
		this.mobileother = mobileother;
	}

	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	public String getModeofpayment() {
		return this.modeofpayment;
	}

	public void setModeofpayment(String modeofpayment) {
		this.modeofpayment = modeofpayment;
	}

	public String getCategoryofstudent() {
		return this.categoryofstudent;
	}

	public void setCategoryofstudent(String categoryofstudent) {
		this.categoryofstudent = categoryofstudent;
	}

	public int getTag() {
		return this.tag;
	}

	public void setTag(int tag) {
		this.tag = tag;
	}

	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	public Date getRegisterationdate() {
		return this.registerationdate;
	}

	public void setRegisterationdate(Date registerationdate) {
		this.registerationdate = registerationdate;
	}

	public Set<TblStudentexamConduct> getTblStudentexamConducts() {
		return this.tblStudentexamConducts;
	}

	public void setTblStudentexamConducts(
			Set<TblStudentexamConduct> tblStudentexamConducts) {
		this.tblStudentexamConducts = tblStudentexamConducts;
	}

	public Set<TblStudentCourseDetails> getTblStudentCourseDetailses() {
		return this.tblStudentCourseDetailses;
	}

	public void setTblStudentCourseDetailses(
			Set<TblStudentCourseDetails> tblStudentCourseDetailses) {
		this.tblStudentCourseDetailses = tblStudentCourseDetailses;
	}

}
