package com.mciter.commonbeans;

// Generated 5 Sep, 2012 1:18:59 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblFontMaster generated by hbm2java
 */
public class TblFontMaster implements java.io.Serializable {

	private Integer fontId;
	private String fontName;
	private String fontPath;
	private int fontTag;
	private String fontSpaceAscii;

	public TblFontMaster() {
	}

	public TblFontMaster(String fontName, String fontPath, int fontTag,
			String fontSpaceAscii) {
		this.fontName = fontName;
		this.fontPath = fontPath;
		this.fontTag = fontTag;
		this.fontSpaceAscii = fontSpaceAscii;
	}

	public Integer getFontId() {
		return this.fontId;
	}

	public void setFontId(Integer fontId) {
		this.fontId = fontId;
	}

	public String getFontName() {
		return this.fontName;
	}

	public void setFontName(String fontName) {
		this.fontName = fontName;
	}

	public String getFontPath() {
		return this.fontPath;
	}

	public void setFontPath(String fontPath) {
		this.fontPath = fontPath;
	}

	public int getFontTag() {
		return this.fontTag;
	}

	public void setFontTag(int fontTag) {
		this.fontTag = fontTag;
	}

	public String getFontSpaceAscii() {
		return this.fontSpaceAscii;
	}

	public void setFontSpaceAscii(String fontSpaceAscii) {
		this.fontSpaceAscii = fontSpaceAscii;
	}

}
